In [1]:
import pandas as pd

In [37]:
import numpy as np

In [2]:
macas = pd.Series( [2, 4, 6, 8], name="Macas" )
macas

0    2
1    4
2    6
3    8
Name: Macas, dtype: int64

In [3]:
macas[2]

np.int64(6)

In [4]:
macas = pd.Series( [2, 4, 6, 8], index=["joao", "camila", "maria", "alfredo"] ,name="Macas" )
macas

joao       2
camila     4
maria      6
alfredo    8
Name: Macas, dtype: int64

In [5]:
macas["joao"]

np.int64(2)

In [6]:
macas["maria"]

np.int64(6)

In [7]:
macas = [2, 4, 6, 8, 10] 
laranjas = [3, 5, 7, 9, 11]

d = {"macas": macas, "laranjas": laranjas}

# df = pd.DataFrame(d)
# df

df = pd.DataFrame(d, index=["joao", "maria", "alvaro", "leticia", "pedro"])
df

         macas  laranjas
joao         2         3
maria        4         5
alvaro       6         7
leticia      8         9
pedro       10        11

In [8]:
df["laranjas"]["alvaro"]

np.int64(7)

In [9]:
df["laranjas"]

joao        3
maria       5
alvaro      7
leticia     9
pedro      11
Name: laranjas, dtype: int64

In [10]:
df["macas"].iloc[3]

np.int64(8)

In [11]:
# df = pd.DataFrame.from_dict(d, orient="index")
# df
df = pd.DataFrame.from_dict(d, orient="index", columns=["joao", "maria", "alvaro", "leticia", "pedro"])
df

          joao  maria  alvaro  leticia  pedro
macas        2      4       6        8     10
laranjas     3      5       7        9     11

In [12]:
df.iat[0, 1]

np.int64(4)

In [13]:
df_imdb = pd.read_csv("C:\\git\\dados\\nlp\\imdb-reviews-pt-br.csv", encoding="utf-8")

In [14]:
df_imdb

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [15]:
df_imdb.head(3)

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg

In [16]:
df_imdb.tail(3)

,id,text_en,text_pt,sentiment
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [17]:
df_imdb.describe()

                 id
count  49459.000000
mean   24730.960917
std    14277.792868
min        1.000000
25%    12366.500000
50%    24731.000000
75%    37095.500000
max    49460.000000

In [18]:
df_imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 49459 entries, 0 to 49458
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         49459 non-null  int64
 1   text_en    49459 non-null  str
 2   text_pt    49459 non-null  str
 3   sentiment  49459 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.5 MB

In [19]:
df_imdb.shape

(49459, 4)

In [20]:
df_imdb2 = pd.concat([df_imdb, df_imdb])
df_imdb2.shape

(98918, 4)

In [21]:
df_imdb2.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49454     True
49455     True
49456     True
49457     True
49458     True
Length: 98918, dtype: bool

In [22]:
temp_df = df_imdb2.drop_duplicates() 
temp_df.shape

(49459, 4)

In [23]:
df_imdb2.shape

(98918, 4)

In [24]:
df_imdb2.drop_duplicates(inplace=True)
df_imdb2.shape

(49459, 4)

In [25]:
df_imdb2

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [27]:
df_imdb2.pop("nova_coluna")
df_imdb2

KeyError: 'nova_coluna'

In [28]:
df_imdb2.drop(index=[2:10000], axis=0 ,inplace=True)
df_imdb2

SyntaxError: invalid syntax (3136611208.py, line 1)

In [29]:
df_imdb2[df_imdb2["sentiment"] == "pos"]

,id,text_en,text_pt,sentiment
12389,12391,I went and saw this movie last night after bei...,Eu fui e vi este filme ontem à noite depois de...,pos
12390,12392,Actor turned director Bill Paxton follows up h...,"O diretor do ator, Bill Paxton, segue sua prom...",pos
12391,12393,As a recreational golfer with some knowledge o...,Como um jogador de recreio com algum conhecime...,pos
12392,12394,"I saw this film in a sneak preview, and it is ...","Eu vi esse filme em uma prévia, e é delicioso....",pos
12393,12395,Bill Paxton has taken the true story of the 19...,Bill Paxton levou a verdadeira história do gol...,pos
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [30]:
df_imdb2["sentiment"].unique()

<StringArray>
['neg', 'pos']
Length: 2, dtype: str

In [31]:
df_imdb2["sentiment_number"] = df_imdb2["sentiment"].replace(["neg", "pos"], [0, 1])
df_imdb2

,id,text_en,text_pt,sentiment,sentiment_number
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg,0
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg,0
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1

In [32]:
df_imdb2["text_pt"].str.split(" ")

0        [Mais, uma, vez,, o, Sr., Costner, arrumou, um...
1        [Este, é, um, exemplo, do, motivo, pelo, qual,...
2        [Primeiro, de, tudo, eu, odeio, esses, raps, i...
3        [Nem, mesmo, os, Beatles, puderam, escrever, m...
4        [Filmes, de, fotos, de, latão, não, é, uma, pa...
                               ...
49454    [Como, a, média, de, votos, era, muito, baixa,...
49455    [O, enredo, teve, algumas, reviravoltas, infel...
49456    [Estou, espantado, com, a, forma, como, este, ...
49457    [A, Christmas, Together, realmente, veio, ante...
49458    [O, drama, romântico, da, classe, trabalhadora...
Name: text_pt, Length: 49459, dtype: object

In [33]:
def contar_palavras( texto : str ) -> int:
    palavras = texto.split(" ")
    return len(palavras)

In [34]:
df_imdb2["text_pt"]

0        Mais uma vez, o Sr. Costner arrumou um filme p...
1        Este é um exemplo do motivo pelo qual a maiori...
2        Primeiro de tudo eu odeio esses raps imbecis, ...
3        Nem mesmo os Beatles puderam escrever músicas ...
4        Filmes de fotos de latão não é uma palavra apr...
                               ...
49454    Como a média de votos era muito baixa, e o fat...
49455    O enredo teve algumas reviravoltas infelizes e...
49456    Estou espantado com a forma como este filme e ...
49457    A Christmas Together realmente veio antes do m...
49458    O drama romântico da classe trabalhadora do di...
Name: text_pt, Length: 49459, dtype: str

In [35]:
df_imdb2["text_pt"].apply( contar_palavras )

0        168
1        245
2        213
3        324
4        244
        ...
49454    106
49455     55
49456    431
49457    180
49458    181
Name: text_pt, Length: 49459, dtype: int64

In [38]:
cat = pd.Categorical(["a", "c", "c", np.nan], categories=["b", "a", "c"])
df = pd.DataFrame({"cat": cat, "s":["a", "c", "c", np.nan]})
print(df.describe())
print(df["cat"].describe())

       cat  s
count    3  3
unique   2  2
top      c  c
freq     2  2
count     3
unique    2
top       c
freq      2
Name: cat, dtype: object

In [39]:
df

   cat    s
0    a    a
1    c    c
2    c    c
3  NaN  NaN

In [40]:
cat = pd.Categorical(['a', 'b', 'c', 'a', 'b', 'c'])
print(cat)

['a', 'b', 'c', 'a', 'b', 'c']
Categories (3, str): ['a', 'b', 'c']

In [41]:
df_imdb2

,id,text_en,text_pt,sentiment,sentiment_number
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg,0
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg,0
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1

In [43]:
df_imdb2[df_imdb2["id"] % 6 == 0]

,id,text_en,text_pt,sentiment,sentiment_number
5,6,"A funny thing happened to me while watching ""M...",Uma coisa engraçada aconteceu comigo enquanto ...,neg,0
11,12,"First of all, I would like to say that I am a ...","Primeiro de tudo, eu gostaria de dizer que sou...",neg,0
17,18,Earth has been destroyed in a nuclear holocaus...,A terra foi destruída em um holocausto nuclear...,neg,0
23,24,"Sure, most of the slasher films of the 1980s w...","Claro, a maioria dos filmes de terror da décad...",neg,0
29,30,"Supercraptastic slasher fare, which feels over...","Receita de slash supercraptástico, que parece ...",neg,0
...,...,...,...,...,...
49432,49434,"I have to say, I loved Vanishing Point. Ive se...","Eu tenho que dizer, eu amei Vanishing Point. E...",pos,1
49438,49440,"This movie is about basically human relations,...",Este filme é basicamente sobre relações humana...,pos,1
49444,49446,I had a chance to see a screening of this movi...,Eu tive a chance de ver uma exibição desse fil...,pos,1
49450,49452,"""Life stinks"" is a parody of life and death, h...","""A vida cheira mal"" é uma paródia de vida e mo...",pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1

In [50]:
df_imdb2[df_imdb2["id"] > 20000]

,id,text_en,text_pt,sentiment,sentiment_number
19999,20001,Gore hounds beware...this is not your movie. T...,Gore hounds beware ... este não é o seu filme....,pos,1
20000,20002,"I just saw the movie, through Netflix. I was i...","Acabei de ver o filme, através do Netflix. Fiq...",pos,1
20001,20003,"As a kid I loved the song ""Never smile at a cr...","Quando criança eu amei a música ""Nunca sorria ...",pos,1
20002,20004,This low budget crocodile movie really deliver...,Este filme de crocodilo de baixo orçamento rea...,pos,1
20003,20005,"""Black Water"" is one of the most tense films I...","""Black Water"" é um dos filmes mais tensos que ...",pos,1
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1