In [1]:
import pandas as pd

In [8]:
macas = pd.Series( [2, 4, 6, 8], name="Macas" )
macas

0    2
1    4
2    6
3    8
Name: Macas, dtype: int64

In [9]:
macas[2]

np.int64(6)

In [10]:
macas = pd.Series( [2, 4, 6, 8], index=["joao", "camila", "maria", "alfredo"] ,name="Macas" )
macas

joao       2
camila     4
maria      6
alfredo    8
Name: Macas, dtype: int64

In [6]:
macas["joao"]

np.int64(2)

In [7]:
macas["maria"]

np.int64(6)

In [15]:
macas = [2, 4, 6, 8, 10] 
laranjas = [3, 5, 7, 9, 11]

d = {"macas": macas, "laranjas": laranjas}

# df = pd.DataFrame(d)
# df

df = pd.DataFrame(d, index=["joao", "maria", "alvaro", "leticia", "pedro"])
df

         macas  laranjas
joao         2         3
maria        4         5
alvaro       6         7
leticia      8         9
pedro       10        11

In [16]:
df["laranjas"]["alvaro"]

np.int64(7)

In [17]:
df["laranjas"]

joao        3
maria       5
alvaro      7
leticia     9
pedro      11
Name: laranjas, dtype: int64

In [29]:
df["macas"].iloc[3]

np.int64(8)

In [31]:
# df = pd.DataFrame.from_dict(d, orient="index")
# df
df = pd.DataFrame.from_dict(d, orient="index", columns=["joao", "maria", "alvaro", "leticia", "pedro"])
df

          joao  maria  alvaro  leticia  pedro
macas        2      4       6        8     10
laranjas     3      5       7        9     11

In [43]:
df.iat[0, 1]

np.int64(4)

In [35]:
df_imdb = pd.read_csv("C:\\git\\dados\\nlp\\imdb-reviews-pt-br.csv", encoding="utf-8")

In [36]:
df_imdb

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [38]:
df_imdb.head(3)

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg

In [39]:
df_imdb.tail(3)

,id,text_en,text_pt,sentiment
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [40]:
df_imdb.describe()

                 id
count  49459.000000
mean   24730.960917
std    14277.792868
min        1.000000
25%    12366.500000
50%    24731.000000
75%    37095.500000
max    49460.000000

In [44]:
df_imdb.info()

<class 'pandas.DataFrame'>
RangeIndex: 49459 entries, 0 to 49458
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         49459 non-null  int64
 1   text_en    49459 non-null  str
 2   text_pt    49459 non-null  str
 3   sentiment  49459 non-null  str
dtypes: int64(1), str(3)
memory usage: 1.5 MB

In [45]:
df_imdb.shape

(49459, 4)

In [47]:
df_imdb2 = pd.concat([df_imdb, df_imdb])
df_imdb2.shape

(98918, 4)

In [48]:
df_imdb2.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
49454     True
49455     True
49456     True
49457     True
49458     True
Length: 98918, dtype: bool

In [49]:
temp_df = df_imdb2.drop_duplicates() 
temp_df.shape

(49459, 4)

In [50]:
df_imdb2.shape

(98918, 4)

In [51]:
df_imdb2.drop_duplicates(inplace=True)
df_imdb2.shape

(49459, 4)

In [52]:
df_imdb2

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [60]:
df_imdb2["nova_coluna"] = (df_imdb2["id"] * 2) + df_imdb2["sentiment"]
df_imdb2

,id,text_en,text_pt,sentiment,nova_coluna
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg,0 2\n1 4\n2 6...
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg,0 2\n1 4\n2 6...
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0 2\n1 4\n2 6...
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0 2\n1 4\n2 6...
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0 2\n1 4\n2 6...
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,0 2\n1 4\n2 6...
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,0 2\n1 4\n2 6...
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,0 2\n1 4\n2 6...
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,0 2\n1 4\n2 6...
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,0 2\n1 4\n2 6...

In [61]:
df_imdb2.pop("nova_coluna")
df_imdb2

,id,text_en,text_pt,sentiment
0,1,Once again Mr. Costner has dragged out a movie...,"Mais uma vez, o Sr. Costner arrumou um filme p...",neg
1,2,This is an example of why the majority of acti...,Este é um exemplo do motivo pelo qual a maiori...,neg
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [69]:
df_imdb2.drop(index=[2:10000], axis=0 ,inplace=True)
df_imdb2

SyntaxError: invalid syntax (3136611208.py, line 1)

In [74]:
df_imdb2[df_imdb2["sentiment"] == "pos"]

,id,text_en,text_pt,sentiment
12389,12391,I went and saw this movie last night after bei...,Eu fui e vi este filme ontem à noite depois de...,pos
12390,12392,Actor turned director Bill Paxton follows up h...,"O diretor do ator, Bill Paxton, segue sua prom...",pos
12391,12393,As a recreational golfer with some knowledge o...,Como um jogador de recreio com algum conhecime...,pos
12392,12394,"I saw this film in a sneak preview, and it is ...","Eu vi esse filme em uma prévia, e é delicioso....",pos
12393,12395,Bill Paxton has taken the true story of the 19...,Bill Paxton levou a verdadeira história do gol...,pos
...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos

In [77]:
df_imdb2["sentiment"].unique()

<StringArray>
['neg', 'pos']
Length: 2, dtype: str

In [78]:
df_imdb2["sentiment_number"] = df_imdb2["sentiment"].replace(["neg", "pos"], [0, 1])
df_imdb2

,id,text_en,text_pt,sentiment,sentiment_number
2,3,"First of all I hate those moronic rappers, who...","Primeiro de tudo eu odeio esses raps imbecis, ...",neg,0
3,4,Not even the Beatles could write songs everyon...,Nem mesmo os Beatles puderam escrever músicas ...,neg,0
4,5,Brass pictures movies is not a fitting word fo...,Filmes de fotos de latão não é uma palavra apr...,neg,0
5,6,"A funny thing happened to me while watching ""M...",Uma coisa engraçada aconteceu comigo enquanto ...,neg,0
6,7,This German horror film has to be one of the w...,Este filme de terror alemão tem que ser um dos...,neg,0
...,...,...,...,...,...
49454,49456,"Seeing as the vote average was pretty low, and...","Como a média de votos era muito baixa, e o fat...",pos,1
49455,49457,"The plot had some wretched, unbelievable twist...",O enredo teve algumas reviravoltas infelizes e...,pos,1
49456,49458,I am amazed at how this movieand most others h...,Estou espantado com a forma como este filme e ...,pos,1
49457,49459,A Christmas Together actually came before my t...,A Christmas Together realmente veio antes do m...,pos,1
49458,49460,Working-class romantic drama from director Mar...,O drama romântico da classe trabalhadora do di...,pos,1

In [83]:
df_imdb2["text_pt"].str.split(" ")

2        [Primeiro, de, tudo, eu, odeio, esses, raps, i...
3        [Nem, mesmo, os, Beatles, puderam, escrever, m...
4        [Filmes, de, fotos, de, latão, não, é, uma, pa...
5        [Uma, coisa, engraçada, aconteceu, comigo, enq...
6        [Este, filme, de, terror, alemão, tem, que, se...
                               ...
49454    [Como, a, média, de, votos, era, muito, baixa,...
49455    [O, enredo, teve, algumas, reviravoltas, infel...
49456    [Estou, espantado, com, a, forma, como, este, ...
49457    [A, Christmas, Together, realmente, veio, ante...
49458    [O, drama, romântico, da, classe, trabalhadora...
Name: text_pt, Length: 49456, dtype: object

In [84]:
def contar_palavras( texto : str ) -> int:
    palavras = texto.split(" ")
    return len(palavras)

In [85]:
df_imdb2["text_pt"]

2        Primeiro de tudo eu odeio esses raps imbecis, ...
3        Nem mesmo os Beatles puderam escrever músicas ...
4        Filmes de fotos de latão não é uma palavra apr...
5        Uma coisa engraçada aconteceu comigo enquanto ...
6        Este filme de terror alemão tem que ser um dos...
                               ...
49454    Como a média de votos era muito baixa, e o fat...
49455    O enredo teve algumas reviravoltas infelizes e...
49456    Estou espantado com a forma como este filme e ...
49457    A Christmas Together realmente veio antes do m...
49458    O drama romântico da classe trabalhadora do di...
Name: text_pt, Length: 49456, dtype: str

In [86]:
df_imdb2["text_pt"].apply( contar_palavras )

2        213
3        324
4        244
5        116
6        161
        ...
49454    106
49455     55
49456    431
49457    180
49458    181
Name: text_pt, Length: 49456, dtype: int64